title: Dennis
email: dennis.as@live.com
description: > # this means to ignore newlines until "baseurl:"
    Este blog foi criado na intenção de reunir algumas coisas que seu mantenedor aprende durante sua caminhada DBA.
baseurl: "/Tardigrade" # the subpath of your site, e.g. /blog
url: "https://dennissenner.github.io/Tardigrade/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dennissenner
github_username:  dennissenner

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
